--
--    NAME
--      ashrptinoop.sql - <one-line expansion of the name>
--
--    DESCRIPTION
--      <short description of component this file declares/defines>
--
--    NOTES
--      <other useful comments, qualifications, etc.>
--
--    MODIFIED   (MM/DD/YY)
--    akini       09/11/08 - ash report do nothing script
--    akini       09/11/08 - Created
--

--
-- Copyright (c) 2008, Oracle and/or its affiliates. All rights reserved.
--
--    NAME
--      ashrptistd.sql - SQL*Plus helper script for obtaining user input
--                       when ASH report is run on standby instance
--
--    DESCRIPTION
--
--
--    NOTES
--      This script expects a variable stdby_flag to be already declared.
--      The user choice (standby/primary) is stored in this variable
--
--    MODIFIED   (MM/DD/YY)
--    akini       09/11/08 - ash report script for user input on standby
--                           instance
--    akini       09/11/08 - Created
--

--
--    NAME
--      awrblmig.sql - AWR Baseline Migrate
--
--    DESCRIPTION
--      This script is used to migrate the AWR Baseline data from
--      the renamed BL tables back to the base tables.  This script is
--      needed because the way the baselines are stored have been changed
--      in 11g.  This script will
--
--    NOTES
--      Run this script if you have AWR Baselines prior to the 11g release
--      and have upgraded to the 11g release.
--
--    MODIFIED   (MM/DD/YY)
--    rburns      11/16/06 - modify set statements
--    mlfeng      06/18/06 - Script to migrate the AWR Baseline data
--    mlfeng      06/18/06 - Created
--
