--------------------------------------------------------------------------------
--
-- Script:      pt.sql (Print Table)
--
-- Purpose:     Executes Tom Kyte print_table routine.
--
-- Copyright:   (c) FTC LLC
--
-- Author:      Velikikh Mikhail
--
-- Usage:       @pt <query>
--              @pt "select username from dba_users where profile='DEFAULT'"
--
-- Versions:
--              Vers:   1.0.0.0
--                Auth: Velikikh M.
--                Date: 2014/04/24 13:23
--                Desc: Creation
--
--------------------------------------------------------------------------------
exec print_table( q'#&1.#')
